// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
///
/// void main() async {
///   WidgetsFlutterBinding.ensureInitialized();
///   await Firebase.initializeApp(
///     options: DefaultFirebaseOptions.currentPlatform,
///   );
///   runApp(MyApp());
/// }
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: 'AIzaSyAdkaskPsfqw4HVzikROGQjkrwb-iu-YEU',
    appId: '1:1042012231539:android:afab801d14a94415c61706',
    messagingSenderId: '1042012231539',
    projectId: 'ayam-chat',
    storageBucket: 'ayam-chat.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: 'AIzaSyAdkaskPsfqw4HVzikROGQjkrwb-iu-YEU',
    appId: '1:1042012231539:ios:placeholder',
    messagingSenderId: '1042012231539',
    projectId: 'ayam-chat',
    storageBucket: 'ayam-chat.firebasestorage.app',
    iosClientId: '1042012231539-467c8hihngos4l2msh09s8lsmb25nf0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayamChat',
  );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyAdkaskPsfqw4HVzikROGQjkrwb-iu-YEU',
    appId: '1:1042012231539:web:placeholder',
    messagingSenderId: '1042012231539',
    projectId: 'ayam-chat',
    storageBucket: 'ayam-chat.firebasestorage.app',
    authDomain: 'ayam-chat.firebaseapp.com',
  );
}
