export interface IconRegistryEntry {
  key: string;
  name: string;
  icon: string;
  category: string;
  files: string[];
}

export const iconRegistry: IconRegistryEntry[] = [
  { key: 'Icons.access_time', name: 'Access Time', icon: 'AccessTime', category: 'ui', files: [] },
  { key: 'Icons.account_balance', name: 'Account Balance', icon: 'AccountBalance', category: 'ui', files: [] },
  { key: 'Icons.account_balance_rounded', name: 'Account Balance Rounded', icon: 'AccountBalance', category: 'ui', files: [] },
  { key: 'Icons.account_balance_wallet', name: 'Account Balance Wallet', icon: 'AccountBalanceWallet', category: 'economy', files: [] },
  { key: 'Icons.account_balance_wallet_rounded', name: 'Account Balance Wallet Rounded', icon: 'AccountBalanceWallet', category: 'economy', files: [] },
  { key: 'Icons.add', name: 'Add', icon: 'Add', category: 'ui', files: [] },
  { key: 'Icons.add_a_photo_outlined', name: 'Add A Photo Outlined', icon: 'AddAPhoto', category: 'media', files: [] },
  { key: 'Icons.add_business', name: 'Add Business', icon: 'AddBusiness', category: 'agency', files: [] },
  { key: 'Icons.add_business_rounded', name: 'Add Business Rounded', icon: 'AddBusiness', category: 'agency', files: [] },
  { key: 'Icons.add_circle_outline', name: 'Add Circle Outline', icon: 'AddCircleOutline', category: 'ui', files: [] },
  { key: 'Icons.add_photo_alternate_rounded', name: 'Add Photo Alternate Rounded', icon: 'AddPhotoAlternate', category: 'media', files: [] },
  { key: 'Icons.add_rounded', name: 'Add Rounded', icon: 'Add', category: 'ui', files: [] },
  { key: 'Icons.admin_panel_settings', name: 'Admin Panel Settings', icon: 'AdminPanelSettings', category: 'agency', files: [] },
  { key: 'Icons.admin_panel_settings_rounded', name: 'Admin Panel Settings Rounded', icon: 'AdminPanelSettings', category: 'agency', files: [] },
  { key: 'Icons.airline_seat_recline_extra', name: 'Airline Seat Recline Extra', icon: 'AirlineSeatReclineExtra', category: 'ui', files: [] },
  { key: 'Icons.alternate_email', name: 'Alternate Email', icon: 'AlternateEmail', category: 'chat', files: [] },
  { key: 'Icons.alternate_email_rounded', name: 'Alternate Email Rounded', icon: 'AlternateEmail', category: 'chat', files: [] },
  { key: 'Icons.arrow_back', name: 'Arrow Back', icon: 'ArrowBack', category: 'economy', files: [] },
  { key: 'Icons.arrow_back_ios', name: 'Arrow Back Ios', icon: 'ArrowBackIos', category: 'economy', files: [] },
  { key: 'Icons.arrow_back_ios_new', name: 'Arrow Back Ios New', icon: 'ArrowBackIos', category: 'economy', files: [] },
  { key: 'Icons.arrow_back_ios_new_rounded', name: 'Arrow Back Ios New Rounded', icon: 'ArrowBackIos', category: 'economy', files: [] },
  { key: 'Icons.arrow_back_ios_rounded', name: 'Arrow Back Ios Rounded', icon: 'ArrowBackIos', category: 'economy', files: [] },
  { key: 'Icons.arrow_downward', name: 'Arrow Downward', icon: 'ArrowDownward', category: 'navigation', files: [] },
  { key: 'Icons.arrow_downward_rounded', name: 'Arrow Downward Rounded', icon: 'ArrowDownward', category: 'navigation', files: [] },
  { key: 'Icons.arrow_drop_down', name: 'Arrow Drop Down', icon: 'ArrowDropDown', category: 'navigation', files: [] },
  { key: 'Icons.arrow_forward_ios', name: 'Arrow Forward Ios', icon: 'ArrowForwardIos', category: 'navigation', files: [] },
  { key: 'Icons.arrow_forward_ios_rounded', name: 'Arrow Forward Ios Rounded', icon: 'ArrowForwardIos', category: 'navigation', files: [] },
  { key: 'Icons.arrow_forward_rounded', name: 'Arrow Forward Rounded', icon: 'ArrowForward', category: 'navigation', files: [] },
  { key: 'Icons.arrow_upward', name: 'Arrow Upward', icon: 'ArrowUpward', category: 'navigation', files: [] },
  { key: 'Icons.arrow_upward_rounded', name: 'Arrow Upward Rounded', icon: 'ArrowUpward', category: 'navigation', files: [] },
  { key: 'Icons.assignment', name: 'Assignment', icon: 'Assignment', category: 'ui', files: [] },
  { key: 'Icons.assignment_late_outlined', name: 'Assignment Late Outlined', icon: 'AssignmentLate', category: 'ui', files: [] },
  { key: 'Icons.audiotrack', name: 'Audiotrack', icon: 'Audiotrack', category: 'audio', files: [] },
  { key: 'Icons.auto_awesome', name: 'Auto Awesome', icon: 'AutoAwesome', category: 'rankings', files: [] },
  { key: 'Icons.backpack', name: 'Backpack', icon: 'Backpack', category: 'economy', files: [] },
  { key: 'Icons.bar_chart_rounded', name: 'Bar Chart Rounded', icon: 'BarChart', category: 'ui', files: [] },
  { key: 'Icons.badge', name: 'Badge', icon: 'Badge', category: 'agency', files: [] },
  { key: 'Icons.badge_outlined', name: 'Badge Outlined', icon: 'Badge', category: 'agency', files: [] },
  { key: 'Icons.badge_rounded', name: 'Badge Rounded', icon: 'Badge', category: 'agency', files: [] },
  { key: 'Icons.block', name: 'Block', icon: 'Block', category: 'vip', files: [] },
  { key: 'Icons.block_outlined', name: 'Block Outlined', icon: 'Block', category: 'vip', files: [] },
  { key: 'Icons.bolt', name: 'Bolt', icon: 'Bolt', category: 'ui', files: [] },
  { key: 'Icons.bolt_rounded', name: 'Bolt Rounded', icon: 'Bolt', category: 'ui', files: [] },
  { key: 'Icons.bookmark', name: 'Bookmark', icon: 'Bookmark', category: 'ui', files: [] },
  { key: 'Icons.bookmark_border', name: 'Bookmark Border', icon: 'BookmarkBorder', category: 'ui', files: [] },
  { key: 'Icons.broken_image', name: 'Broken Image', icon: 'BrokenImage', category: 'media', files: [] },
  { key: 'Icons.business', name: 'Business', icon: 'Business', category: 'agency', files: [] },
  { key: 'Icons.business_center', name: 'Business Center', icon: 'BusinessCenter', category: 'agency', files: [] },
  { key: 'Icons.business_outlined', name: 'Business Outlined', icon: 'Business', category: 'agency', files: [] },
  { key: 'Icons.business_rounded', name: 'Business Rounded', icon: 'Business', category: 'agency', files: [] },
  { key: 'Icons.cake', name: 'Cake', icon: 'Cake', category: 'ui', files: [] },
  { key: 'Icons.calendar_today_rounded', name: 'Calendar Today Rounded', icon: 'CalendarToday', category: 'ui', files: [] },
  { key: 'Icons.camera_alt', name: 'Camera Alt', icon: 'Camera', category: 'media', files: [] },
  { key: 'Icons.camera_alt_outlined', name: 'Camera Alt Outlined', icon: 'Camera', category: 'media', files: [] },
  { key: 'Icons.camera_alt_rounded', name: 'Camera Alt Rounded', icon: 'Camera', category: 'media', files: [] },
  { key: 'Icons.camera_rounded', name: 'Camera Rounded', icon: 'Camera', category: 'media', files: [] },
  { key: 'Icons.campaign', name: 'Campaign', icon: 'Campaign', category: 'ui', files: [] },
  { key: 'Icons.cancel', name: 'Cancel', icon: 'Cancel', category: 'ui', files: [] },
  { key: 'Icons.card_giftcard', name: 'Card Giftcard', icon: 'CardGiftcard', category: 'ui', files: [] },
  { key: 'Icons.card_giftcard_rounded', name: 'Card Giftcard Rounded', icon: 'CardGiftcard', category: 'ui', files: [] },
  { key: 'Icons.casino_rounded', name: 'Casino Rounded', icon: 'Casino', category: 'ui', files: [] },
  { key: 'Icons.castle_rounded', name: 'Castle Rounded', icon: 'Castle', category: 'ui', files: [] },
  { key: 'Icons.category_outlined', name: 'Category Outlined', icon: 'Category', category: 'ui', files: [] },
  { key: 'Icons.chair', name: 'Chair', icon: 'Chair', category: 'ui', files: [] },
  { key: 'Icons.chat', name: 'Chat', icon: 'Chat', category: 'chat', files: [] },
  { key: 'Icons.chat_active', name: 'Chat Active', icon: 'Chat', category: 'chat', files: [] },
  { key: 'Icons.chat_bubble_outline', name: 'Chat Bubble Outline', icon: 'ChatBubbleOutline', category: 'chat', files: [] },
  { key: 'Icons.chat_bubble_outline_rounded', name: 'Chat Bubble Outline Rounded', icon: 'ChatBubbleOutline', category: 'chat', files: [] },
  { key: 'Icons.chat_bubble_rounded', name: 'Chat Bubble Rounded', icon: 'ChatBubble', category: 'chat', files: [] },
  { key: 'Icons.check', name: 'Check', icon: 'Check', category: 'ui', files: [] },
  { key: 'Icons.check_circle', name: 'Check Circle', icon: 'CheckCircle', category: 'ui', files: [] },
  { key: 'Icons.check_circle_agency', name: 'Check Circle Agency', icon: 'CheckCircleAgency', category: 'agency', files: [] },
  { key: 'Icons.check_circle_outline', name: 'Check Circle Outline', icon: 'CheckCircleOutline', category: 'ui', files: [] },
  { key: 'Icons.check_circle_rounded', name: 'Check Circle Rounded', icon: 'CheckCircle', category: 'ui', files: [] },
  { key: 'Icons.check_circle_ui', name: 'Check Circle Ui', icon: 'CheckCircleUi', category: 'ui', files: [] },
  { key: 'Icons.chevron_left', name: 'Chevron Left', icon: 'ChevronLeft', category: 'navigation', files: [] },
  { key: 'Icons.chevron_left_rounded', name: 'Chevron Left Rounded', icon: 'ChevronLeft', category: 'navigation', files: [] },
  { key: 'Icons.chevron_right_rounded', name: 'Chevron Right Rounded', icon: 'ChevronRight', category: 'navigation', files: [] },
  { key: 'Icons.circle', name: 'Circle', icon: 'Circle', category: 'ui', files: [] },
  { key: 'Icons.clear', name: 'Clear', icon: 'Clear', category: 'ui', files: [] },
  { key: 'Icons.close', name: 'Close', icon: 'Close', category: 'navigation', files: [] },
  { key: 'Icons.close_rounded', name: 'Close Rounded', icon: 'Close', category: 'navigation', files: [] },
  { key: 'Icons.comment_outlined', name: 'Comment Outlined', icon: 'Comment', category: 'chat', files: [] },
  { key: 'Icons.copy', name: 'Copy', icon: 'Copy', category: 'ui', files: [] },
  { key: 'Icons.crop_square_outlined', name: 'Crop Square Outlined', icon: 'CropSquare', category: 'ui', files: [] },
  { key: 'Icons.currency_bitcoin', name: 'Currency Bitcoin', icon: 'CurrencyBitcoin', category: 'economy', files: [] },
  { key: 'Icons.currency_bitcoin_rounded', name: 'Currency Bitcoin Rounded', icon: 'CurrencyBitcoin', category: 'economy', files: [] },
  { key: 'Icons.currency_exchange', name: 'Currency Exchange', icon: 'CurrencyExchange', category: 'ui', files: [] },
  { key: 'Icons.dashboard_rounded', name: 'Dashboard Rounded', icon: 'Dashboard', category: 'ui', files: [] },
  { key: 'Icons.delete', name: 'Delete', icon: 'Delete', category: 'ui', files: [] },
  { key: 'Icons.delete_forever', name: 'Delete Forever', icon: 'DeleteForever', category: 'ui', files: [] },
  { key: 'Icons.delete_forever_rounded', name: 'Delete Forever Rounded', icon: 'DeleteForever', category: 'ui', files: [] },
  { key: 'Icons.delete_outline', name: 'Delete Outline', icon: 'DeleteOutline', category: 'ui', files: [] },
  { key: 'Icons.delete_outline_rounded', name: 'Delete Outline Rounded', icon: 'DeleteOutline', category: 'ui', files: [] },
  { key: 'Icons.description_rounded', name: 'Description Rounded', icon: 'Description', category: 'ui', files: [] },
  { key: 'Icons.description_rounded_agency', name: 'Description Rounded Agency', icon: 'DescriptionRoundedAgency', category: 'agency', files: [] },
  { key: 'Icons.description_rounded_misc', name: 'Description Rounded Misc', icon: 'DescriptionRoundedMisc', category: 'ui', files: [] },
  { key: 'Icons.diamond', name: 'Diamond', icon: 'Diamond', category: 'economy', files: [] },
  { key: 'Icons.diamond_rounded', name: 'Diamond Rounded', icon: 'Diamond', category: 'economy', files: [] },
  { key: 'Icons.directions_car', name: 'Directions Car', icon: 'DirectionsCar', category: 'ui', files: [] },
  { key: 'Icons.directions_car_rounded', name: 'Directions Car Rounded', icon: 'DirectionsCar', category: 'ui', files: [] },
  { key: 'Icons.download', name: 'Download', icon: 'Download', category: 'navigation', files: [] },
  { key: 'Icons.edit', name: 'Edit', icon: 'Edit', category: 'ui', files: [] },
  { key: 'Icons.edit_outlined', name: 'Edit Outlined', icon: 'Edit', category: 'ui', files: [] },
  { key: 'Icons.edit_rounded', name: 'Edit Rounded', icon: 'Edit', category: 'ui', files: [] },
  { key: 'Icons.email', name: 'Email', icon: 'Email', category: 'chat', files: [] },
  { key: 'Icons.email_rounded', name: 'Email Rounded', icon: 'Email', category: 'chat', files: [] },
  { key: 'Icons.emoji_events', name: 'Emoji Events', icon: 'EmojiEvents', category: 'rankings', files: [] },
  { key: 'Icons.emoji_events_outlined', name: 'Emoji Events Outlined', icon: 'EmojiEvents', category: 'rankings', files: [] },
  { key: 'Icons.emoji_events_rounded', name: 'Emoji Events Rounded', icon: 'EmojiEvents', category: 'rankings', files: [] },
  { key: 'Icons.error', name: 'Error', icon: 'Error', category: 'ui', files: [] },
  { key: 'Icons.error_outline', name: 'Error Outline', icon: 'ErrorOutline', category: 'ui', files: [] },
  { key: 'Icons.error_outline_rounded', name: 'Error Outline Rounded', icon: 'ErrorOutline', category: 'ui', files: [] },
  { key: 'Icons.event', name: 'Event', icon: 'Event', category: 'ui', files: [] },
  { key: 'Icons.event_rounded', name: 'Event Rounded', icon: 'Event', category: 'ui', files: [] },
  { key: 'Icons.exit_to_app', name: 'Exit To App', icon: 'ExitToApp', category: 'navigation', files: [] },
  { key: 'Icons.exit_to_app_rounded', name: 'Exit To App Rounded', icon: 'ExitToApp', category: 'navigation', files: [] },
  { key: 'Icons.explore_outlined', name: 'Explore Outlined', icon: 'Explore', category: 'ui', files: [] },
  { key: 'Icons.face', name: 'Face', icon: 'Face', category: 'users', files: [] },
  { key: 'Icons.face_retouching_natural', name: 'Face Retouching Natural', icon: 'FaceRetouchingNatural', category: 'users', files: [] },
  { key: 'Icons.facebook', name: 'Facebook', icon: 'Facebook', category: 'users', files: [] },
  { key: 'Icons.family_restroom', name: 'Family Restroom', icon: 'FamilyRestroom', category: 'ui', files: [] },
  { key: 'Icons.family_restroom_rounded', name: 'Family Restroom Rounded', icon: 'FamilyRestroom', category: 'ui', files: [] },
  { key: 'Icons.favorite', name: 'Favorite', icon: 'Favorite', category: 'ui', files: [] },
  { key: 'Icons.favorite_border', name: 'Favorite Border', icon: 'FavoriteBorder', category: 'ui', files: [] },
  { key: 'Icons.favorite_border_rounded', name: 'Favorite Border Rounded', icon: 'FavoriteBorder', category: 'ui', files: [] },
  { key: 'Icons.favorite_outlined', name: 'Favorite Outlined', icon: 'Favorite', category: 'ui', files: [] },
  { key: 'Icons.favorite_rounded', name: 'Favorite Rounded', icon: 'Favorite', category: 'ui', files: [] },
  { key: 'Icons.female', name: 'Female', icon: 'Female', category: 'users', files: [] },
  { key: 'Icons.fiber_manual_record_rounded', name: 'Fiber Manual Record Rounded', icon: 'FiberManualRecord', category: 'ui', files: [] },
  { key: 'Icons.flag', name: 'Flag', icon: 'Flag', category: 'agency', files: [] },
  { key: 'Icons.flag_outlined', name: 'Flag Outlined', icon: 'Flag', category: 'agency', files: [] },
  { key: 'Icons.flag_rounded', name: 'Flag Rounded', icon: 'Flag', category: 'agency', files: [] },
  { key: 'Icons.flutter_dash', name: 'Flutter Dash', icon: 'FlutterDash', category: 'ui', files: [] },
  { key: 'Icons.folder_open', name: 'Folder Open', icon: 'FolderOpen', category: 'ui', files: [] },
  { key: 'Icons.forum_outlined', name: 'Forum Outlined', icon: 'Forum', category: 'chat', files: [] },
  { key: 'Icons.forum_rounded', name: 'Forum Rounded', icon: 'Forum', category: 'chat', files: [] },
  { key: 'Icons.g_mobiledata', name: 'G Mobiledata', icon: 'GMobiledata', category: 'ui', files: [] },
  { key: 'Icons.gavel_rounded', name: 'Gavel Rounded', icon: 'Gavel', category: 'ui', files: [] },
  { key: 'Icons.graphic_eq_rounded', name: 'Graphic Eq Rounded', icon: 'GraphicEq', category: 'audio', files: [] },
  { key: 'Icons.group', name: 'Group', icon: 'Group', category: 'users', files: [] },
  { key: 'Icons.group_add_rounded', name: 'Group Add Rounded', icon: 'GroupAdd', category: 'users', files: [] },
  { key: 'Icons.group_outlined', name: 'Group Outlined', icon: 'Group', category: 'users', files: [] },
  { key: 'Icons.groups_rounded', name: 'Groups Rounded', icon: 'Groups', category: 'users', files: [] },
  { key: 'Icons.headset_off', name: 'Headset Off', icon: 'HeadsetOff', category: 'audio', files: [] },
  { key: 'Icons.history', name: 'History', icon: 'History', category: 'agency', files: [] },
  { key: 'Icons.home', name: 'Home', icon: 'Home', category: 'ui', files: [] },
  { key: 'Icons.home_active', name: 'Home Active', icon: 'Home', category: 'ui', files: [] },
  { key: 'Icons.home_outlined', name: 'Home Outlined', icon: 'Home', category: 'ui', files: [] },
  { key: 'Icons.home_rounded', name: 'Home Rounded', icon: 'Home', category: 'ui', files: [] },
  { key: 'Icons.hourglass_top', name: 'Hourglass Top', icon: 'HourglassTop', category: 'ui', files: [] },
  { key: 'Icons.house_outlined', name: 'House Outlined', icon: 'House', category: 'ui', files: [] },
  { key: 'Icons.image', name: 'Image', icon: 'Image', category: 'media', files: [] },
  { key: 'Icons.image_not_supported', name: 'Image Not Supported', icon: 'ImageNotSupported', category: 'media', files: [] },
  { key: 'Icons.image_outlined', name: 'Image Outlined', icon: 'Image', category: 'media', files: [] },
  { key: 'Icons.image_rounded', name: 'Image Rounded', icon: 'Image', category: 'media', files: [] },
  { key: 'Icons.info_outline', name: 'Info Outline', icon: 'InfoOutline', category: 'ui', files: [] },
  { key: 'Icons.info_outline_rounded', name: 'Info Outline Rounded', icon: 'InfoOutline', category: 'ui', files: [] },
  { key: 'Icons.inventory_2_outlined', name: 'Inventory 2 Outlined', icon: 'Inventory2', category: 'ui', files: [] },
  { key: 'Icons.inventory_2_rounded', name: 'Inventory 2 Rounded', icon: 'Inventory2', category: 'ui', files: [] },
  { key: 'Icons.ios_share_rounded', name: 'Ios Share Rounded', icon: 'IosShare', category: 'social', files: [] },
  { key: 'Icons.keyboard_arrow_down', name: 'Keyboard Arrow Down', icon: 'KeyboardArrowDown', category: 'navigation', files: [] },
  { key: 'Icons.keyboard_arrow_down_rounded', name: 'Keyboard Arrow Down Rounded', icon: 'KeyboardArrowDown', category: 'navigation', files: [] },
  { key: 'Icons.keyboard_arrow_up_rounded', name: 'Keyboard Arrow Up Rounded', icon: 'KeyboardArrowUp', category: 'navigation', files: [] },
  { key: 'Icons.leaderboard', name: 'Leaderboard', icon: 'Leaderboard', category: 'rankings', files: [] },
  { key: 'Icons.leaderboard_rounded', name: 'Leaderboard Rounded', icon: 'Leaderboard', category: 'rankings', files: [] },
  { key: 'Icons.link', name: 'Link', icon: 'Link', category: 'social', files: [] },
  { key: 'Icons.local_fire_department', name: 'Local Fire Department', icon: 'LocalFireDepartment', category: 'ui', files: [] },
  { key: 'Icons.local_florist_rounded', name: 'Local Florist Rounded', icon: 'LocalFlorist', category: 'ui', files: [] },
  { key: 'Icons.local_offer', name: 'Local Offer', icon: 'LocalOffer', category: 'ui', files: [] },
  { key: 'Icons.local_offer_rounded', name: 'Local Offer Rounded', icon: 'LocalOffer', category: 'ui', files: [] },
  { key: 'Icons.local_shipping_outlined', name: 'Local Shipping Outlined', icon: 'LocalShipping', category: 'ui', files: [] },
  { key: 'Icons.lock', name: 'Lock', icon: 'Lock', category: 'vip', files: [] },
  { key: 'Icons.lock_open_rounded', name: 'Lock Open Rounded', icon: 'LockOpen', category: 'vip', files: [] },
  { key: 'Icons.lock_outline', name: 'Lock Outline', icon: 'LockOutline', category: 'vip', files: [] },
  { key: 'Icons.lock_outline_rounded', name: 'Lock Outline Rounded', icon: 'LockOutline', category: 'vip', files: [] },
  { key: 'Icons.lock_rounded', name: 'Lock Rounded', icon: 'Lock', category: 'vip', files: [] },
  { key: 'Icons.logout', name: 'Logout', icon: 'Logout', category: 'navigation', files: [] },
  { key: 'Icons.logout_rounded', name: 'Logout Rounded', icon: 'Logout', category: 'navigation', files: [] },
  { key: 'Icons.mail_outline', name: 'Mail Outline', icon: 'MailOutline', category: 'chat', files: [] },
  { key: 'Icons.male', name: 'Male', icon: 'Male', category: 'users', files: [] },
  { key: 'Icons.meeting_room', name: 'Meeting Room', icon: 'MeetingRoom', category: 'ui', files: [] },
  { key: 'Icons.meeting_room_outlined', name: 'Meeting Room Outlined', icon: 'MeetingRoom', category: 'ui', files: [] },
  { key: 'Icons.message', name: 'Message', icon: 'Message', category: 'chat', files: [] },
  { key: 'Icons.message_rounded', name: 'Message Rounded', icon: 'Message', category: 'chat', files: [] },
  { key: 'Icons.mic', name: 'Mic', icon: 'Mic', category: 'audio', files: [] },
  { key: 'Icons.mic_none', name: 'Mic None', icon: 'MicNone', category: 'audio', files: [] },
  { key: 'Icons.mic_off', name: 'Mic Off', icon: 'MicOff', category: 'audio', files: [] },
  { key: 'Icons.mic_off_rounded', name: 'Mic Off Rounded', icon: 'MicOff', category: 'audio', files: [] },
  { key: 'Icons.mic_rounded', name: 'Mic Rounded', icon: 'Mic', category: 'audio', files: [] },
  { key: 'Icons.military_tech', name: 'Military Tech', icon: 'MilitaryTech', category: 'rankings', files: [] },
  { key: 'Icons.military_tech_outlined', name: 'Military Tech Outlined', icon: 'MilitaryTech', category: 'rankings', files: [] },
  { key: 'Icons.military_tech_rounded', name: 'Military Tech Rounded', icon: 'MilitaryTech', category: 'rankings', files: [] },
  { key: 'Icons.minimize', name: 'Minimize', icon: 'Minimize', category: 'navigation', files: [] },
  { key: 'Icons.minimize_rounded', name: 'Minimize Rounded', icon: 'Minimize', category: 'navigation', files: [] },
  { key: 'Icons.monetization_on', name: 'Monetization On', icon: 'MonetizationOn', category: 'ui', files: [] },
  { key: 'Icons.more_vert', name: 'More Vert', icon: 'MoreVert', category: 'navigation', files: [] },
  { key: 'Icons.movie_creation_outlined', name: 'Movie Creation Outlined', icon: 'MovieCreation', category: 'ui', files: [] },
  { key: 'Icons.music_note', name: 'Music Note', icon: 'MusicNote', category: 'audio', files: [] },
  { key: 'Icons.music_off', name: 'Music Off', icon: 'MusicOff', category: 'audio', files: [] },
  { key: 'Icons.notes_rounded', name: 'Notes Rounded', icon: 'Notes', category: 'ui', files: [] },
  { key: 'Icons.notification_important', name: 'Notification Important', icon: 'NotificationImportant', category: 'ui', files: [] },
  { key: 'Icons.notifications', name: 'Notifications', icon: 'Notifications', category: 'chat', files: [] },
  { key: 'Icons.notifications_active', name: 'Notifications Active', icon: 'Notifications', category: 'chat', files: [] },
  { key: 'Icons.notifications_outlined', name: 'Notifications Outlined', icon: 'Notifications', category: 'chat', files: [] },
  { key: 'Icons.outbound_rounded', name: 'Outbound Rounded', icon: 'Outbound', category: 'ui', files: [] },
  { key: 'Icons.pause', name: 'Pause', icon: 'Pause', category: 'audio', files: [] },
  { key: 'Icons.pause_circle', name: 'Pause Circle', icon: 'PauseCircle', category: 'audio', files: [] },
  { key: 'Icons.pause_rounded', name: 'Pause Rounded', icon: 'Pause', category: 'audio', files: [] },
  { key: 'Icons.payment_rounded', name: 'Payment Rounded', icon: 'Payment', category: 'economy', files: [] },
  { key: 'Icons.payments_outlined', name: 'Payments Outlined', icon: 'Payments', category: 'economy', files: [] },
  { key: 'Icons.people', name: 'People', icon: 'People', category: 'users', files: [] },
  { key: 'Icons.people_alt', name: 'People Alt', icon: 'People', category: 'users', files: [] },
  { key: 'Icons.people_outline', name: 'People Outline', icon: 'PeopleOutline', category: 'users', files: [] },
  { key: 'Icons.people_rounded', name: 'People Rounded', icon: 'People', category: 'users', files: [] },
  { key: 'Icons.perm_identity', name: 'Perm Identity', icon: 'PermIdentity', category: 'users', files: [] },
  { key: 'Icons.person', name: 'Person', icon: 'Person', category: 'users', files: [] },
  { key: 'Icons.person_active', name: 'Person Active', icon: 'Person', category: 'users', files: [] },
  { key: 'Icons.person_add', name: 'Person Add', icon: 'PersonAdd', category: 'users', files: [] },
  { key: 'Icons.person_add_alt_1', name: 'Person Add Alt 1', icon: 'PersonAdd', category: 'users', files: [] },
  { key: 'Icons.person_add_alt_1_rounded', name: 'Person Add Alt 1 Rounded', icon: 'PersonAdd', category: 'users', files: [] },
  { key: 'Icons.person_add_outlined', name: 'Person Add Outlined', icon: 'PersonAdd', category: 'users', files: [] },
  { key: 'Icons.person_add_rounded', name: 'Person Add Rounded', icon: 'PersonAdd', category: 'users', files: [] },
  { key: 'Icons.person_off', name: 'Person Off', icon: 'PersonOff', category: 'users', files: [] },
  { key: 'Icons.person_outline', name: 'Person Outline', icon: 'PersonOutline', category: 'users', files: [] },
  { key: 'Icons.person_outline_rounded', name: 'Person Outline Rounded', icon: 'PersonOutline', category: 'users', files: [] },
  { key: 'Icons.person_pin_rounded', name: 'Person Pin Rounded', icon: 'PersonPin', category: 'users', files: [] },
  { key: 'Icons.person_remove', name: 'Person Remove', icon: 'PersonRemove', category: 'users', files: [] },
  { key: 'Icons.person_rounded', name: 'Person Rounded', icon: 'Person', category: 'users', files: [] },
  { key: 'Icons.person_search_rounded', name: 'Person Search Rounded', icon: 'PersonSearch', category: 'navigation', files: [] },
  { key: 'Icons.phone', name: 'Phone', icon: 'Phone', category: 'chat', files: [] },
  { key: 'Icons.phone_android', name: 'Phone Android', icon: 'PhoneAndroid', category: 'chat', files: [] },
  { key: 'Icons.phone_iphone_rounded', name: 'Phone Iphone Rounded', icon: 'PhoneIphone', category: 'chat', files: [] },
  { key: 'Icons.phone_rounded', name: 'Phone Rounded', icon: 'Phone', category: 'chat', files: [] },
  { key: 'Icons.photo_library_rounded', name: 'Photo Library Rounded', icon: 'PhotoLibrary', category: 'media', files: [] },
  { key: 'Icons.play_arrow', name: 'Play Arrow', icon: 'PlayArrow', category: 'navigation', files: [] },
  { key: 'Icons.play_arrow_rounded', name: 'Play Arrow Rounded', icon: 'PlayArrow', category: 'navigation', files: [] },
  { key: 'Icons.play_circle', name: 'Play Circle', icon: 'PlayCircle', category: 'audio', files: [] },
  { key: 'Icons.play_circle_outline', name: 'Play Circle Outline', icon: 'PlayCircleOutline', category: 'audio', files: [] },
  { key: 'Icons.portrait', name: 'Portrait', icon: 'Portrait', category: 'users', files: [] },
  { key: 'Icons.power_settings_new_rounded', name: 'Power Settings New Rounded', icon: 'PowerSettings', category: 'agency', files: [] },
  { key: 'Icons.privacy_tip_outlined', name: 'Privacy Tip Outlined', icon: 'PrivacyTip', category: 'ui', files: [] },
  { key: 'Icons.qr_code_2_rounded', name: 'Qr Code 2 Rounded', icon: 'QrCode2', category: 'ui', files: [] },
  { key: 'Icons.radio_button_checked', name: 'Radio Button Checked', icon: 'RadioButtonChecked', category: 'ui', files: [] },
  { key: 'Icons.radio_button_off', name: 'Radio Button Off', icon: 'RadioButtonOff', category: 'ui', files: [] },
  { key: 'Icons.receipt_long', name: 'Receipt Long', icon: 'ReceiptLong', category: 'economy', files: [] },
  { key: 'Icons.receipt_long_outlined', name: 'Receipt Long Outlined', icon: 'ReceiptLong', category: 'economy', files: [] },
  { key: 'Icons.redeem', name: 'Redeem', icon: 'Redeem', category: 'economy', files: [] },
  { key: 'Icons.refresh', name: 'Refresh', icon: 'Refresh', category: 'navigation', files: [] },
  { key: 'Icons.refresh_rounded', name: 'Refresh Rounded', icon: 'Refresh', category: 'navigation', files: [] },
  { key: 'Icons.remove_circle_outline', name: 'Remove Circle Outline', icon: 'RemoveCircleOutline', category: 'ui', files: [] },
  { key: 'Icons.remove_rounded', name: 'Remove Rounded', icon: 'Remove', category: 'ui', files: [] },
  { key: 'Icons.rocket_launch', name: 'Rocket Launch', icon: 'RocketLaunch', category: 'ui', files: [] },
  { key: 'Icons.rocket_launch_rounded', name: 'Rocket Launch Rounded', icon: 'RocketLaunch', category: 'ui', files: [] },
  { key: 'Icons.search', name: 'Search', icon: 'Search', category: 'navigation', files: [] },
  { key: 'Icons.search_rounded', name: 'Search Rounded', icon: 'Search', category: 'navigation', files: [] },
  { key: 'Icons.security_rounded', name: 'Security Rounded', icon: 'Security', category: 'ui', files: [] },
  { key: 'Icons.sell_rounded', name: 'Sell Rounded', icon: 'Sell', category: 'ui', files: [] },
  { key: 'Icons.send', name: 'Send', icon: 'Send', category: 'chat', files: [] },
  { key: 'Icons.send_rounded', name: 'Send Rounded', icon: 'Send', category: 'chat', files: [] },
  { key: 'Icons.settings', name: 'Settings', icon: 'Settings', category: 'agency', files: [] },
  { key: 'Icons.settings_outlined', name: 'Settings Outlined', icon: 'Settings', category: 'agency', files: [] },
  { key: 'Icons.settings_rounded', name: 'Settings Rounded', icon: 'Settings', category: 'agency', files: [] },
  { key: 'Icons.share_rounded', name: 'Share Rounded', icon: 'Share', category: 'social', files: [] },
  { key: 'Icons.shield_outlined', name: 'Shield Outlined', icon: 'Shield', category: 'agency', files: [] },
  { key: 'Icons.shopping_bag', name: 'Shopping Bag', icon: 'ShoppingBag', category: 'economy', files: [] },
  { key: 'Icons.smart_toy_outlined', name: 'Smart Toy Outlined', icon: 'SmartToy', category: 'ui', files: [] },
  { key: 'Icons.star', name: 'Star', icon: 'Star', category: 'rankings', files: [] },
  { key: 'Icons.star_outline', name: 'Star Outline', icon: 'StarOutline', category: 'rankings', files: [] },
  { key: 'Icons.star_rounded', name: 'Star Rounded', icon: 'Star', category: 'rankings', files: [] },
  { key: 'Icons.stars', name: 'Stars', icon: 'Stars', category: 'rankings', files: [] },
  { key: 'Icons.stars_rounded', name: 'Stars Rounded', icon: 'Stars', category: 'rankings', files: [] },
  { key: 'Icons.store', name: 'Store', icon: 'Store', category: 'economy', files: [] },
  { key: 'Icons.storefront_rounded', name: 'Storefront Rounded', icon: 'Storefront', category: 'economy', files: [] },
  { key: 'Icons.supervisor_account_rounded', name: 'Supervisor Account Rounded', icon: 'SupervisorAccount', category: 'agency', files: [] },
  { key: 'Icons.support_agent_rounded', name: 'Support Agent Rounded', icon: 'SupportAgent', category: 'ui', files: [] },
  { key: 'Icons.sync_alt', name: 'Sync Alt', icon: 'Sync', category: 'ui', files: [] },
  { key: 'Icons.system_update_alt', name: 'System Update Alt', icon: 'SystemUpdate', category: 'ui', files: [] },
  { key: 'Icons.tag', name: 'Tag', icon: 'Tag', category: 'ui', files: [] },
  { key: 'Icons.task_alt', name: 'Task Alt', icon: 'Task', category: 'ui', files: [] },
  { key: 'Icons.task_alt_rounded', name: 'Task Alt Rounded', icon: 'Task', category: 'ui', files: [] },
  { key: 'Icons.telegram', name: 'Telegram', icon: 'Telegram', category: 'social', files: [] },
  { key: 'Icons.title_rounded', name: 'Title Rounded', icon: 'Title', category: 'ui', files: [] },
  { key: 'Icons.today', name: 'Today', icon: 'Today', category: 'ui', files: [] },
  { key: 'Icons.timer', name: 'Timer', icon: 'Timer', category: 'ui', files: [] },
  { key: 'Icons.trending_up', name: 'Trending Up', icon: 'TrendingUp', category: 'ui', files: [] },
  { key: 'Icons.trending_up_rounded', name: 'Trending Up Rounded', icon: 'TrendingUp', category: 'ui', files: [] },
  { key: 'Icons.trophyIcon', name: 'TrophyIcon', icon: 'TrophyIcon', category: 'rankings', files: [] },
  { key: 'Icons.tune_rounded', name: 'Tune Rounded', icon: 'Tune', category: 'ui', files: [] },
  { key: 'Icons.verified', name: 'Verified', icon: 'Verified', category: 'rankings', files: [] },
  { key: 'Icons.verified_outlined', name: 'Verified Outlined', icon: 'Verified', category: 'rankings', files: [] },
  { key: 'Icons.verified_rounded', name: 'Verified Rounded', icon: 'Verified', category: 'rankings', files: [] },
  { key: 'Icons.verified_user_rounded', name: 'Verified User Rounded', icon: 'VerifiedUser', category: 'rankings', files: [] },
  { key: 'Icons.vertical_align_bottom', name: 'Vertical Align Bottom', icon: 'VerticalAlignBottom', category: 'ui', files: [] },
  { key: 'Icons.vibration_rounded', name: 'Vibration Rounded', icon: 'Vibration', category: 'ui', files: [] },
  { key: 'Icons.videocam_outlined', name: 'Videocam Outlined', icon: 'Videocam', category: 'media', files: [] },
  { key: 'Icons.vip_center', name: 'Vip Center', icon: 'VipCenter', category: 'vip', files: [] },
  { key: 'Icons.volume_mute', name: 'Volume Mute', icon: 'VolumeMute', category: 'audio', files: [] },
  { key: 'Icons.volume_off', name: 'Volume Off', icon: 'VolumeOff', category: 'audio', files: [] },
  { key: 'Icons.volume_off_outlined', name: 'Volume Off Outlined', icon: 'VolumeOff', category: 'audio', files: [] },
  { key: 'Icons.volume_up', name: 'Volume Up', icon: 'VolumeUp', category: 'audio', files: [] },
  { key: 'Icons.vpn_key_rounded', name: 'Vpn Key Rounded', icon: 'VpnKey', category: 'ui', files: [] },
  { key: 'Icons.warning_amber', name: 'Warning Amber', icon: 'WarningAmber', category: 'ui', files: [] },
  { key: 'Icons.warning_rounded', name: 'Warning Rounded', icon: 'Warning', category: 'ui', files: [] },
  { key: 'Icons.whatshot', name: 'Whatshot', icon: 'Whatshot', category: 'rankings', files: [] },
  { key: 'Icons.wifi', name: 'Wifi', icon: 'Wifi', category: 'ui', files: [] },
  { key: 'Icons.workspace_premium', name: 'Workspace Premium', icon: 'WorkspacePremium', category: 'rankings', files: [] },
  { key: 'Icons.workspace_premium_outlined', name: 'Workspace Premium Outlined', icon: 'WorkspacePremium', category: 'rankings', files: [] },
  { key: 'Icons.workspace_premium_rounded', name: 'Workspace Premium Rounded', icon: 'WorkspacePremium', category: 'rankings', files: [] },
];
