export interface ScreenAssetEntry {
  constant: string;
  path: string;
  fullKey: string;
}

export const SCREEN_ASSETS: Record<string, { label: string; assets: ScreenAssetEntry[] }> = {
  'الغرفة': {
    label: '🎙 الغرفة',
    assets: [
      { constant: 'roomBgFriend', path: 'assets/mipmap-xxhdpi/room_bg_friend.webp', fullKey: 'assets_mipmap-xxhdpi_room_bg_friend_webp' },
      { constant: 'roomSetMusicIc', path: 'assets/mipmap-xxhdpi/room_set_music_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_music_ic_webp' },
      { constant: 'roomMicCharmMaleIc', path: 'assets/mipmap-xxhdpi/room_mic_charm_male_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_charm_male_ic_webp' },
      { constant: 'roomGiftPanelSelectOwnerIc', path: 'assets/mipmap-xxhdpi/room_gift_panel_select_owner_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_panel_select_owner_ic_webp' },
      { constant: 'roomGiftLuckyIntroduceBg', path: 'assets/mipmap-xxhdpi/room_gift_lucky_introduce_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_lucky_introduce_bg_webp' },
      { constant: 'roomBgSeatPre', path: 'assets/mipmap-xxhdpi/room_bg_seat_pre.webp', fullKey: 'assets_mipmap-xxhdpi_room_bg_seat_pre_webp' },
      { constant: 'roomMicphoneIc', path: 'assets/mipmap-xxhdpi/room_micphone_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_micphone_ic_webp' },
      { constant: 'roomMicphoneCloseIc', path: 'assets/mipmap-xxhdpi/room_micphone_close_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_micphone_close_ic_webp' },
      { constant: 'roomGiftIc', path: 'assets/mipmap-xxhdpi/room_gift_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_ic_webp' },
      { constant: 'roomEmojIc', path: 'assets/mipmap-xxhdpi/room_emoj_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_emoj_ic_webp' },
      { constant: 'roomChatIc', path: 'assets/mipmap-xxhdpi/room_chat_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_chat_ic_webp' },
      { constant: 'roomFunctionIc', path: 'assets/mipmap-xxhdpi/room_function_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_function_ic_webp' },
      { constant: 'roomMsgIc', path: 'assets/mipmap-xxhdpi/room_msg_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_msg_ic_webp' },
      { constant: 'roomExitIc', path: 'assets/mipmap-xxhdpi/room_exit_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_exit_ic_webp' },
      { constant: 'roomGameIc', path: 'assets/mipmap-xxhdpi/room_game_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_game_ic_webp' },
      { constant: 'roomMusicEmptyIc', path: 'assets/mipmap-xxhdpi/room_music_empty_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_music_empty_ic_webp' },
      { constant: 'roomMicOn', path: 'assets/mipmap-xxhdpi/room_mic_on.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_on_webp' },
      { constant: 'roomMicOff', path: 'assets/mipmap-xxhdpi/room_mic_off.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_off_webp' },
      { constant: 'roomMicDown', path: 'assets/mipmap-xxhdpi/room_mic_down.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_down_webp' },
      { constant: 'roomMicSeatDefaultIc', path: 'assets/mipmap-xxhdpi/room_mic_seat_default_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_seat_default_ic_webp' },
      { constant: 'roomMicSeatBigIc', path: 'assets/mipmap-xxhdpi/room_mic_seat_big_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_seat_big_ic_webp' },
      { constant: 'roomMicSeatLockIc', path: 'assets/mipmap-xxhdpi/room_mic_seat_lock_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_seat_lock_ic_webp' },
      { constant: 'roomMicSeatMuteIc', path: 'assets/mipmap-xxhdpi/room_mic_seat_mute_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_seat_mute_ic_webp' },
      { constant: 'roomLockStateIc', path: 'assets/mipmap-xxhdpi/room_lock_state_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_lock_state_ic_webp' },
      { constant: 'roomPwdLockOffIc', path: 'assets/mipmap-xxhdpi/room_pwd_lock_off_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_pwd_lock_off_ic_webp' },
      { constant: 'roomPwdLockOpen', path: 'assets/mipmap-xxhdpi/room_pwd_lock_open.webp', fullKey: 'assets_mipmap-xxhdpi_room_pwd_lock_open_webp' },
      { constant: 'roomHotLogoIc', path: 'assets/mipmap-xxhdpi/room_hot_logo_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_hot_logo_ic_webp' },
      { constant: 'roomCreateRoomBg', path: 'assets/mipmap-xxhdpi/room_create_room_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_create_room_bg_webp' },
      { constant: 'roomCreateLabelIc', path: 'assets/mipmap-xxhdpi/room_create_label_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_create_label_ic_webp' },
      { constant: 'roomCameraLogoIc', path: 'assets/mipmap-xxhdpi/room_camera_logo_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_camera_logo_ic_webp' },
      { constant: 'roomNoticeBg', path: 'assets/mipmap-xxhdpi/room_gift_notice_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_notice_bg_webp' },
      { constant: 'roomGiftImgPre', path: 'assets/mipmap-xxhdpi/room_gift_img_pre.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_img_pre_webp' },
      { constant: 'roomWindowFloatBg', path: 'assets/mipmap-xxhdpi/room_window_float_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_window_float_bg_webp' },
      { constant: 'roomPackageGiftBg', path: 'assets/drawable/room_package_gift_bg.xml', fullKey: 'assets_drawable_room_package_gift_bg_xml' },
      { constant: 'roomGiftPanelHeaderMemberPre', path: 'assets/drawable/room_gift_panel_header_member_pre.xml', fullKey: 'assets_drawable_room_gift_panel_header_member_pre_xml' },
      { constant: 'roomGiftPanelHeaderMemberNor', path: 'assets/drawable/room_gift_panel_header_member_nor.xml', fullKey: 'assets_drawable_room_gift_panel_header_member_nor_xml' },
      { constant: 'roomGiftPanelHeaderMemberSelectNumBg', path: 'assets/drawable/room_gift_panel_header_member_select_num_bg.xml', fullKey: 'assets_drawable_room_gift_panel_header_member_select_num_bg_xml' },
      { constant: 'roomGiftTabBagIc', path: 'assets/mipmap-xxhdpi/room_gift_tab_bag_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_tab_bag_ic_webp' },
      { constant: 'roomGiftAllSelectNor', path: 'assets/mipmap-xxhdpi/room_gift_all_select_nor.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_all_select_nor_webp' },
      { constant: 'roomGiftAllSelectPre', path: 'assets/mipmap-xxhdpi/room_gift_all_select_pre.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_all_select_pre_webp' },
      { constant: 'roomGiftNumOpenIc', path: 'assets/mipmap-xxhdpi/room_gift_num_open_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_num_open_ic_webp' },
      { constant: 'roomGiftNoticeBg2', path: 'assets/mipmap-xxhdpi/room_gift_notice_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_notice_bg2_webp' },
      { constant: 'roomGiftLuckyBg', path: 'assets/mipmap-xxhdpi/room_gift_lucky_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_lucky_bg_webp' },
      { constant: 'roomGiftComboTimeIc', path: 'assets/mipmap-xxhdpi/room_gift_combo_time_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_combo_time_ic_webp' },
      { constant: 'roomGiftComboLuckyPre', path: 'assets/mipmap-xxhdpi/room_gift_combo_lucky_pre.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_combo_lucky_pre_webp' },
      { constant: 'roomGiftComboLuckyNor', path: 'assets/mipmap-xxhdpi/room_gift_combo_lucky_nor.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_combo_lucky_nor_webp' },
      { constant: 'roomGiftLuckyLabelIc', path: 'assets/mipmap-xxhdpi/room_gift_lucky_label_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_lucky_label_ic_webp' },
      { constant: 'roomGiftStarLabelIc', path: 'assets/mipmap-xxhdpi/room_gift_star_label_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_star_label_ic_webp' },
      { constant: 'roomGiftMusicLabelIc', path: 'assets/mipmap-xxhdpi/room_gift_music_label_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_gift_music_label_ic_webp' },
      { constant: 'roomLuckyGiftAnimBg', path: 'assets/mipmap-xxhdpi/room_lucky_gift_anim_bg.webp', fullKey: 'assets_mipmap-xxhdpi_room_lucky_gift_anim_bg_webp' },
      { constant: 'roomLuckyGiftCoinIc', path: 'assets/mipmap-xxhdpi/room_lucky_gift_coin_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_lucky_gift_coin_ic_webp' },
      { constant: 'roomLuckyGiftBg2', path: 'assets/mipmap-xxhdpi/room_lucky_gift_bg_2.webp', fullKey: 'assets_mipmap-xxhdpi_room_lucky_gift_bg_2_webp' },
      { constant: 'roomSetVolumeIc', path: 'assets/mipmap-xxhdpi/room_set_volume_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_volume_ic_webp' },
      { constant: 'roomSetVolumeCloseIc', path: 'assets/mipmap-xxhdpi/room_set_volume_close_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_volume_close_ic_webp' },
      { constant: 'roomSetSetIc', path: 'assets/mipmap-xxhdpi/room_set_set_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_set_ic_webp' },
      { constant: 'roomSetSeatStyle', path: 'assets/mipmap-xxhdpi/room_set_seat_style.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_seat_style_webp' },
      { constant: 'roomSetReportIc', path: 'assets/mipmap-xxhdpi/room_set_report_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_report_ic_webp' },
      { constant: 'roomSetMixerIc', path: 'assets/mipmap-xxhdpi/room_set_mixer_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_mixer_ic_webp' },
      { constant: 'roomSetGiftIc', path: 'assets/mipmap-xxhdpi/room_set_gift_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_gift_ic_webp' },
      { constant: 'roomSetEffectIc', path: 'assets/mipmap-xxhdpi/room_set_effect_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_set_effect_ic_webp' },
      { constant: 'roomOnlineInfoBg', path: 'assets/mipmap-xxhdpi/room_online_info_bg.9.png', fullKey: 'assets_mipmap-xxhdpi_room_online_info_bg_9_png' },
      { constant: 'roomWindowFloatCancel', path: 'assets/mipmap-xxhdpi/room_window_float_cancel_ic.png', fullKey: 'assets_mipmap-xxhdpi_room_window_float_cancel_ic_png' },
      { constant: 'roomUserInfoGiftIc', path: 'assets/mipmap-xxhdpi/room_user_info_gift_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_user_info_gift_ic_webp' },
      { constant: 'icSocialSharing', path: 'assets/mipmap-xxhdpi/ic_social_sharing.webp', fullKey: 'assets_mipmap-xxhdpi_ic_social_sharing_webp' },
      { constant: 'commonBtnDianNor', path: 'assets/mipmap-xxhdpi/common_btn_dian_nor.webp', fullKey: 'assets_mipmap-xxhdpi_common_btn_dian_nor_webp' },
      { constant: 'commonBtnDianPre', path: 'assets/mipmap-xxhdpi/common_btn_dian_pre.webp', fullKey: 'assets_mipmap-xxhdpi_common_btn_dian_pre_webp' },
      { constant: 'nextWhiteIc', path: 'assets/mipmap-xxhdpi/next_white_ic.webp', fullKey: 'assets_mipmap-xxhdpi_next_white_ic_webp' },
      { constant: 'roomUserFollowNorIc', path: 'assets/mipmap-xxhdpi/room_user_follow_nor_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_user_follow_nor_ic_webp' },
      { constant: 'roomUserFollowPreIc', path: 'assets/mipmap-xxhdpi/room_user_follow_pre_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_user_follow_pre_ic_webp' },
      { constant: 'roomUserChatIc', path: 'assets/mipmap-xxhdpi/room_user_chat_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_user_chat_ic_webp' },
      { constant: 'roomMicOperateAtSign', path: 'assets/mipmap-xxhdpi/room_mic_operate_at_sign.webp', fullKey: 'assets_mipmap-xxhdpi_room_mic_operate_at_sign_webp' },
      { constant: 'roomUserinfoMoreIc', path: 'assets/mipmap-xxhdpi/room_userinfo_more_ic.webp', fullKey: 'assets_mipmap-xxhdpi_room_userinfo_more_ic_webp' },
      { constant: 'roomFollowNor', path: 'assets/mipmap-xxhdpi/room_follow_nor.webp', fullKey: 'assets_mipmap-xxhdpi_room_follow_nor_webp' },
      { constant: 'roomFollowPre', path: 'assets/mipmap-xxhdpi/room_follow_pre.webp', fullKey: 'assets_mipmap-xxhdpi_room_follow_pre_webp' },
      { constant: 'nextBlack', path: 'assets/mipmap-xxhdpi/next_black.webp', fullKey: 'assets_mipmap-xxhdpi_next_black_webp' },
      { constant: 'roomOwnerInfoRoomBg', path: 'assets/mipmap-xxhdpi/room_owner_info_room_bg.9.png', fullKey: 'assets_mipmap-xxhdpi_room_owner_info_room_bg_9_png' },
      { constant: 'next2Ic', path: 'assets/mipmap-xxhdpi/next_2_ic.webp', fullKey: 'assets_mipmap-xxhdpi_next_2_ic_webp' },
    ],
  },
  'الشات': {
    label: '💬 الشات',
    assets: [
      { constant: 'chatMessageSystemBg', path: 'assets/mipmap-xxhdpi/chat_message_system_bg.webp', fullKey: 'assets_mipmap-xxhdpi_chat_message_system_bg_webp' },
      { constant: 'chatMessageInformationBg', path: 'assets/mipmap-xxhdpi/chat_message_information_bg.webp', fullKey: 'assets_mipmap-xxhdpi_chat_message_information_bg_webp' },
    ],
  },
  'الاستكشاف': {
    label: '🔍 الاستكشاف',
    assets: [
      { constant: 'discoverHeaderBg', path: 'assets/mipmap-xxhdpi/discover_header_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_header_bg_webp' },
      { constant: 'discoverSearchIc', path: 'assets/mipmap-xxhdpi/discover_search_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_search_ic_webp' },
      { constant: 'discoverRoomIc', path: 'assets/mipmap-xxhdpi/discover_room_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_ic_webp' },
      { constant: 'discoverTabFollowIc', path: 'assets/mipmap-xxhdpi/discover_tab_follow_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_tab_follow_ic_webp' },
      { constant: 'discoverTabRecentIc', path: 'assets/mipmap-xxhdpi/discover_tab_recent_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_tab_recent_ic_webp' },
      { constant: 'discoverTabIndicatorIc', path: 'assets/mipmap-xxhdpi/discover_tab_indicator_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_tab_indicator_ic_webp' },
      { constant: 'discoverRoomItemInfoBg', path: 'assets/mipmap-xxhdpi/discover_room_item_info_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_item_info_bg_webp' },
      { constant: 'discoverRoomItem1', path: 'assets/mipmap-xxhdpi/discover_room_item_1.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_item_1_webp' },
      { constant: 'discoverItemRoom2', path: 'assets/mipmap-xxhdpi/discover_item_room_2.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_room_2_webp' },
      { constant: 'discoverItemRoom3', path: 'assets/mipmap-xxhdpi/discover_item_room_3.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_room_3_webp' },
      { constant: 'discoverGameTeamingIc', path: 'assets/mipmap-xxhdpi/discover_game_teaming_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_game_teaming_ic_webp' },
      { constant: 'discoverItemChatBg', path: 'assets/mipmap-xxhdpi/discover_item_chat_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_chat_bg_webp' },
      { constant: 'discoverItemMusicBg', path: 'assets/mipmap-xxhdpi/discover_item_music_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_music_bg_webp' },
      { constant: 'discoverItemGameBg', path: 'assets/mipmap-xxhdpi/discover_item_game_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_game_bg_webp' },
      { constant: 'discoverItemHobbyBg', path: 'assets/mipmap-xxhdpi/discover_item_hobby_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_hobby_bg_webp' },
      { constant: 'discoverItemPartyBg', path: 'assets/mipmap-xxhdpi/discover_item_party_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_party_bg_webp' },
      { constant: 'discoverItemFriendBg', path: 'assets/mipmap-xxhdpi/discover_item_friend_bg.webp', fullKey: 'assets_mipmap-xxhdpi_discover_item_friend_bg_webp' },
      { constant: 'discoverRoomChatIc', path: 'assets/mipmap-xxhdpi/discover_room_chat_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_chat_ic_webp' },
      { constant: 'discoverRoomMusicIc', path: 'assets/mipmap-xxhdpi/discover_room_enjoy_music.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_enjoy_music_webp' },
      { constant: 'discoverRoomGameTeamIc', path: 'assets/mipmap-xxhdpi/discover_room_game_team_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_game_team_ic_webp' },
      { constant: 'discoverRoomHobbyIc', path: 'assets/mipmap-xxhdpi/discover_room_hobby_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_hobby_ic_webp' },
      { constant: 'discoverRoomPartyIc', path: 'assets/mipmap-xxhdpi/discover_room_party_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_party_ic_webp' },
      { constant: 'discoverCountryMoreIc', path: 'assets/mipmap-xxhdpi/discover_country_more_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_country_more_ic_webp' },
      { constant: 'discoverRoomHotLabelIc', path: 'assets/mipmap-xxhdpi/discover_room_hot_label_ic.webp', fullKey: 'assets_mipmap-xxhdpi_discover_room_hot_label_ic_webp' },
      { constant: 'placeholderResBannerIc', path: 'assets/mipmap-xxhdpi/placeholder_res_banner_ic.webp', fullKey: 'assets_mipmap-xxhdpi_placeholder_res_banner_ic_webp' },
    ],
  },
  'حسابي': {
    label: '👤 حسابي',
    assets: [
      { constant: 'mineWalletHeaderBg', path: 'assets/mipmap-xxhdpi/mine_wallet_header_bg.webp', fullKey: 'assets_mipmap-xxhdpi_mine_wallet_header_bg_webp' },
      { constant: 'mineWalletCoinBagIc', path: 'assets/mipmap-xxhdpi/mine_wallet_coin_bag_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_wallet_coin_bag_ic_webp' },
      { constant: 'mineWalletDetailIc', path: 'assets/mipmap-xxhdpi/mine_wallet_detail_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_wallet_detail_ic_webp' },
      { constant: 'mineWalletFilterIc', path: 'assets/mipmap-xxhdpi/mine_wallet_filter_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_wallet_filter_ic_webp' },
      { constant: 'mineFacebookIc', path: 'assets/mipmap-xxhdpi/mine_facebook_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_facebook_ic_webp' },
      { constant: 'mineFeedbackIc', path: 'assets/mipmap-xxhdpi/mine_feedback_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_feedback_ic_webp' },
      { constant: 'mineReportIc', path: 'assets/mipmap-xxhdpi/mine_report_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_report_ic_webp' },
      { constant: 'mineCpIc', path: 'assets/mipmap-xxhdpi/mine_setting_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_cp_ic_webp' },
      { constant: 'mineSettingIc', path: 'assets/mipmap-xxhdpi/mine_setting_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_setting_ic_webp' },
      { constant: 'minePhotoAddIc', path: 'assets/mipmap-xxhdpi/mine_photo_add_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_photo_add_ic_webp' },
      { constant: 'mineUnionIc', path: 'assets/mipmap-xxhdpi/mine_union_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_union_ic_webp' },
      { constant: 'minePhoneIc', path: 'assets/mipmap-xxhdpi/mine_phone_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_phone_ic_webp' },
      { constant: 'mineGoogleIc', path: 'assets/mipmap-xxhdpi/mine_google_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_google_ic_webp' },
      { constant: 'mineFollowNorIc', path: 'assets/mipmap-xxhdpi/mine_follow_nor_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_follow_nor_ic_webp' },
      { constant: 'mineFollowPreIc', path: 'assets/mipmap-xxhdpi/mine_follow_pre_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_follow_pre_ic_webp' },
      { constant: 'mineLevelIc', path: 'assets/mipmap-xxhdpi/mine_level_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_level_ic_webp' },
      { constant: 'mineBackpackIc', path: 'assets/mipmap-xxhdpi/mine_backpack_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_backpack_ic_webp' },
      { constant: 'mineMallIc', path: 'assets/mipmap-xxhdpi/mine_mall_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_mall_ic_webp' },
      { constant: 'mineUserEditIc', path: 'assets/mipmap-xxhdpi/mine_user_edit_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_user_edit_ic_webp' },
      { constant: 'mineDeleteIc', path: 'assets/mipmap-xxhdpi/mine_delete_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_delete_ic_webp' },
      { constant: 'mineBlackIc', path: 'assets/mipmap-xxhdpi/mine_black_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_black_ic_webp' },
      { constant: 'mineCloseIc', path: 'assets/mipmap-xxhdpi/mine_close_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_close_ic_webp' },
      { constant: 'mineCameraIc', path: 'assets/mipmap-xxhdpi/mine_camera_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_camera_ic_webp' },
      { constant: 'mineAvatarIc', path: 'assets/mipmap-xxhdpi/mine_avatar_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_avatar_ic_webp' },
      { constant: 'minePhoneDownIc', path: 'assets/mipmap-xxhdpi/mine_phone_down_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_phone_down_ic_webp' },
      { constant: 'mineGooglePayIc', path: 'assets/mipmap-xxhdpi/mine_google_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_google_pay_ic_webp' },
      { constant: 'mineTopBg', path: 'assets/mipmap-xxhdpi/mine_top_bg.webp', fullKey: 'assets_mipmap-xxhdpi_mine_top_bg_webp' },
      { constant: 'mineBtnEditIc', path: 'assets/mipmap-xxhdpi/mine_btn_edit_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_btn_edit_ic_webp' },
      { constant: 'mineWalletIc', path: 'assets/mipmap-xxhdpi/mine_wallet_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_wallet_ic_webp' },
      { constant: 'mineVipCenterBg', path: 'assets/mipmap-xxhdpi/mine_vip_center_bg.webp', fullKey: 'assets_mipmap-xxhdpi_mine_vip_center_bg_webp' },
      { constant: 'mineMallTabVipIc', path: 'assets/mipmap-xxhdpi/mine_mall_tab_vip_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_mall_tab_vip_ic_webp' },
      { constant: 'mineVipLabelIc', path: 'assets/mipmap-xxhdpi/mine_vip_label_ic.webp', fullKey: 'assets_mipmap-xxhdpi_mine_vip_label_ic_webp' },
      { constant: 'mineVipGo', path: 'assets/mipmap-xxhdpi/mine_vip_go.webp', fullKey: 'assets_mipmap-xxhdpi_mine_vip_go_webp' },
      { constant: 'icSexGirl', path: 'assets/mipmap-xxhdpi/ic_sex_girl.webp', fullKey: 'assets_mipmap-xxhdpi_ic_sex_girl_webp' },
      { constant: 'icSexBoy', path: 'assets/mipmap-xxhdpi/ic_sex_boy.webp', fullKey: 'assets_mipmap-xxhdpi_ic_sex_boy_webp' },
      { constant: 'commonUserIdIc', path: 'assets/mipmap-xxhdpi/common_user_id_ic.webp', fullKey: 'assets_mipmap-xxhdpi_common_user_id_ic_webp' },
      { constant: 'commonIdCopyIc', path: 'assets/mipmap-xxhdpi/common_id_copy_ic.webp', fullKey: 'assets_mipmap-xxhdpi_common_id_copy_ic_webp' },
      { constant: 'levelTopBg', path: 'assets/mipmap-xxhdpi/level_top_bg.webp', fullKey: 'assets_mipmap-xxhdpi_level_top_bg_webp' },
    ],
  },
  'عام': {
    label: '🔧 عام',
    assets: [
      { constant: 'backIc', path: 'assets/mipmap-xxhdpi/back_ic.webp', fullKey: 'assets_mipmap-xxhdpi_back_ic_webp' },
      { constant: 'commonCloseIc', path: 'assets/mipmap-xxhdpi/common_close_ic.webp', fullKey: 'assets_mipmap-xxhdpi_common_close_ic_webp' },
      { constant: 'commonGoldIc1', path: 'assets/mipmap-xxhdpi/common_gold_ic_1.webp', fullKey: 'assets_mipmap-xxhdpi_common_gold_ic_1_webp' },
      { constant: 'commonGoldIc2', path: 'assets/mipmap-xxhdpi/common_gold_ic_2.webp', fullKey: 'assets_mipmap-xxhdpi_common_gold_ic_2_webp' },
      { constant: 'commonGoldIc3', path: 'assets/mipmap-xxhdpi/common_gold_ic_3.webp', fullKey: 'assets_mipmap-xxhdpi_common_gold_ic_3_webp' },
      { constant: 'commonGoldIc4', path: 'assets/mipmap-xxhdpi/common_gold_ic_4.webp', fullKey: 'assets_mipmap-xxhdpi_common_gold_ic_4_webp' },
      { constant: 'commonDiamondIc', path: 'assets/mipmap-xxhdpi/common_diamond_ic.webp', fullKey: 'assets_mipmap-xxhdpi_common_diamond_ic_webp' },
      { constant: 'commonNext3Ic', path: 'assets/mipmap-xxhdpi/common_next_3_ic.webp', fullKey: 'assets_mipmap-xxhdpi_common_next_3_ic_webp' },
      { constant: 'commonNext4Ic', path: 'assets/mipmap-xxhdpi/common_next_4_ic.webp', fullKey: 'assets_mipmap-xxhdpi_common_next_4_ic_webp' },
      { constant: 'commonBack2', path: 'assets/mipmap-xxhdpi/common_back_2.webp', fullKey: 'assets_mipmap-xxhdpi_common_back_2_webp' },
      { constant: 'backWhite', path: 'assets/mipmap-xxhdpi/back_white.webp', fullKey: 'assets_mipmap-xxhdpi_back_white_webp' },
      { constant: 'nextBlackIc', path: 'assets/mipmap-xxhdpi/next_black_ic.webp', fullKey: 'assets_mipmap-xxhdpi_next_black_ic_webp' },
      { constant: 'sexMaleIc', path: 'assets/mipmap-xxhdpi/sex_male_ic.webp', fullKey: 'assets_mipmap-xxhdpi_sex_male_ic_webp' },
      { constant: 'sexFemaleIc', path: 'assets/mipmap-xxhdpi/sex_female_ic.webp', fullKey: 'assets_mipmap-xxhdpi_sex_female_ic_webp' },
      { constant: 'avaBoy', path: 'assets/mipmap-xxhdpi/ava_boy.webp', fullKey: 'assets_mipmap-xxhdpi_ava_boy_webp' },
      { constant: 'avaGirl', path: 'assets/mipmap-xxhdpi/ava_girl.webp', fullKey: 'assets_mipmap-xxhdpi_ava_girl_webp' },
    ],
  },
  'التبويبات': {
    label: '📑 التبويبات',
    assets: [
      { constant: 'tabDiscoverNor', path: 'assets/mipmap-xxhdpi/tab_discover_nor.webp', fullKey: 'assets_mipmap-xxhdpi_tab_discover_nor_webp' },
      { constant: 'tabDiscoverPre', path: 'assets/mipmap-xxhdpi/tab_discover_pre.webp', fullKey: 'assets_mipmap-xxhdpi_tab_discover_pre_webp' },
      { constant: 'tabRankingNor', path: 'assets/mipmap-xxhdpi/tab_discover_nor.webp', fullKey: 'assets_mipmap-xxhdpi_tab_ranking_nor_webp' },
      { constant: 'tabRankingPre', path: 'assets/mipmap-xxhdpi/tab_discover_pre.webp', fullKey: 'assets_mipmap-xxhdpi_tab_ranking_pre_webp' },
      { constant: 'tabMessageNor', path: 'assets/mipmap-xxhdpi/tab_message_nor.webp', fullKey: 'assets_mipmap-xxhdpi_tab_message_nor_webp' },
      { constant: 'tabMessagePre', path: 'assets/mipmap-xxhdpi/tab_message_pre.webp', fullKey: 'assets_mipmap-xxhdpi_tab_message_pre_webp' },
      { constant: 'tabMineNor', path: 'assets/mipmap-xxhdpi/tab_mine_nor.webp', fullKey: 'assets_mipmap-xxhdpi_tab_mine_nor_webp' },
      { constant: 'tabMinePre', path: 'assets/mipmap-xxhdpi/tab_mine_pre.webp', fullKey: 'assets_mipmap-xxhdpi_tab_mine_pre_webp' },
    ],
  },
  'SVGA': {
    label: '🎞 SVGA',
    assets: [
      { constant: 'superAdminFrame', path: 'assets/svga/super_admin_frame.svga', fullKey: 'assets_svga_super_admin_frame_svga' },
      { constant: 'giftAnimSvga', path: 'assets/svga/gift_anim.svga', fullKey: 'assets_svga_gift_anim_svga' },
      { constant: 'superAdmin', path: 'assets/svga/super_admin.svga', fullKey: 'assets_svga_super_admin_svga' },
      { constant: 'gift', path: 'assets/svga/gift.svga', fullKey: 'assets_svga_gift_svga' },
      { constant: 'miaoSvga', path: 'assets/svga/miao.svga', fullKey: 'assets_svga_miao_svga' },
      { constant: 'roomFmWaveMale', path: 'assets/svga/room_fm_wave_male.svga', fullKey: 'assets_svga_room_fm_wave_male_svga' },
      { constant: 'roomFmWaveFemale', path: 'assets/svga/room_fm_wave_female.svga', fullKey: 'assets_svga_room_fm_wave_female_svga' },
      { constant: 'roomSpeakingWaveMale', path: 'assets/room_speaking_wave_male.svga', fullKey: 'assets_room_speaking_wave_male_svga' },
      { constant: 'roomSpeakingWaveFemale', path: 'assets/room_speaking_wave_female.svga', fullKey: 'assets_room_speaking_wave_female_svga' },
      { constant: 'roomRankBorder1', path: 'assets/svga/kojuyee_room_rank_border1.svga', fullKey: 'assets_svga_kojuyee_room_rank_border1_svga' },
      { constant: 'roomRankBorder2', path: 'assets/svga/kojuyee_room_rank_border2.svga', fullKey: 'assets_svga_kojuyee_room_rank_border2_svga' },
      { constant: 'roomRankBorder3', path: 'assets/svga/kojuyee_room_rank_border3.svga', fullKey: 'assets_svga_kojuyee_room_rank_border3_svga' },
    ],
  },
  'Lottie': {
    label: '🎬 Lottie',
    assets: [
      { constant: 'lottie3', path: 'assets/lottie/3.json', fullKey: 'assets_lottie_3_json' },
      { constant: 'lottie4', path: 'assets/lottie/4.json', fullKey: 'assets_lottie_4_json' },
      { constant: 'lottie25', path: 'assets/lottie/25.json', fullKey: 'assets_lottie_25_json' },
    ],
  },
  'تسجيل الدخول': {
    label: '🚪 تسجيل الدخول',
    assets: [
      { constant: 'splashImgLogo', path: 'assets/mipmap-xxhdpi/splash_img_logo.webp', fullKey: 'assets_mipmap-xxhdpi_splash_img_logo_webp' },
    ],
  },
};

export const SCREEN_ORDER = ['الغرفة', 'الشات', 'الاستكشاف', 'حسابي', 'عام', 'التبويبات', 'SVGA', 'Lottie', 'تسجيل الدخول'];
